name: Bump snapshot version

on:
  workflow_call:
    inputs:
      next_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      next_version:
        description: 'Next version. Specify <major.minor.patch>, e.g. 7.2.0 (Do NOT include -SNAPSHOT, this will be added automatically)'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-snapshot-version:
    name: Bump snapshot version
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:

      - name: Checkout SDK
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          persist-credentials: true

      - name: Set next version
        env:
          NEXT_VERSION: ${{ inputs.next_version }}
        run: .github/scripts/set-next-version.sh "$NEXT_VERSION"

      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_VERSION: ${{ inputs.next_version }}
          RUN_ID: ${{ github.run_id }}
        run: .github/scripts/create-version-bump-pr.sh "$NEXT_VERSION" "$RUN_ID"
