name: Publish API docs and record SDK version

on:
  workflow_call:
    inputs:
      rc_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      rc_version:
        description: 'SDK version these docs are for. Specify <major.minor.patch> e.g. 7.1.2. It will use the branch "release/<version>".'
        required: true

permissions:
  contents: write

jobs:
  publish-api-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Validate access to version data service
        uses: embrace-io/public-actions/upload-sdk-version@1841c9025e9640e5bbf83db6900b828df30addeb
        with:
          platform: 'android'
          version: ${{ inputs.rc_version }}
          dryRun: true
          uploadUrl: ${{ vars.SDK_VERSION_URL }}
        env:
          SDK_VERSION_TOKEN: ${{ secrets.SDK_VERSION_TOKEN }}

      - name: Configure git
        run: |
          git config --global user.name 'embrace-ci[bot]'
          git config --global user.email 'embrace-ci@users.noreply.github.com'

      - name: Extract base version (major.minor.0)
        id: base_version
        env:
          RC_VERSION: ${{ inputs.rc_version }}
        run: |
          base_version=$(echo "$RC_VERSION" | cut -d. -f1,2).0
          echo "base_version=$base_version" >> $GITHUB_OUTPUT

      - name: Checkout SDK
        uses: actions/checkout@v6
        with:
          ref: release/${{ steps.base_version.outputs.base_version }}
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Generate Documentation
        run: ./gradlew dokkaGenerate

      - name: Publish GitHub Pages
        env:
          RC_VERSION: ${{ inputs.rc_version }}
        run: |
          mv build/dokka/html .docs-newly-generated # new docs generated by previous step
          git checkout gh-pages
          git rm -rf docs # old docs on gh-pages branch
          mv .docs-newly-generated docs
          date > docs/version.txt
          echo ${{ github.sha }} >> docs/version.txt
          echo $RC_VERSION >> docs/version.txt
          git add -f docs
          git config --global user.name "embrace-ci"
          git config --global user.email "embrace-ci@users.noreply.github.com"
          git commit --allow-empty --message "CI/CD: Automatically generated documentation for ${RC_VERSION}" docs/
          git push --force origin gh-pages

      - name: Record SDK Version History
        uses: embrace-io/public-actions/upload-sdk-version@1841c9025e9640e5bbf83db6900b828df30addeb
        with:
          platform: 'android'
          version: ${{ inputs.rc_version }}
          dryRun: false
          uploadUrl: ${{ vars.SDK_VERSION_URL }}
        env:
          SDK_VERSION_TOKEN: ${{ secrets.SDK_VERSION_TOKEN }}
