name: Pre-Release - Update Test Apps with new Snapshot

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: 'Next version. Specify <major.minor>, e.g. 6.4 (Do NOT include -SNAPSHOT, will be added automatically)'
        required: true
  workflow_call:
    inputs:
      next_version:
        required: true
        type: string

jobs:
  update-apps:
    name: Update Apps Repo
    strategy:
      fail-fast: false
      matrix:
        repo: [ embrace-io/android-sdk-benchmark, embrace-io/android-test-suite, embrace-io/ndk-test-app-ndkbuild, embrace-io/ndk-test-app-custombuild, embrace-io/ndk-test-app, embrace-io/android-size-measure ]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.name 'embrace-ci[bot]'
          git config --global user.email 'embrace-ci@users.noreply.github.com'

      - name: Checkout App
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          ref: master
          token: ${{ secrets.GH_ANDROID_SDK_TOKEN }} # NOTE: write embrace-io/android-sdk-benchmark, embrace-io/android-test-suite, embrace-io/ndk-test-app-ndkbuild, embrace-io/ndk-test-app-custombuild, embrace-io/ndk-test-app, embrace-io/android-size-measure

      - name: Set next SDK version
        run: |
          git checkout master
          sed -i -r "s#swazzler_version = ([^\']+)#swazzler_version = ${{ github.event.inputs.next_version }}.0-SNAPSHOT#" gradle.properties
          git add gradle.properties
          git commit -m "CI/CD: set next version: ${{ github.event.inputs.next_version }}.0-SNAPSHOT"
          git push
